using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using System.Windows;

namespace StellarDownloader
{
    public partial class MainWindow : Window
    {
        private const string GITHUB_BASE_RAW_URL = "http://188.157.212.145:3001/";

        private readonly HttpClient _httpClient;

        public MainWindow()
        {
            InitializeComponent();
            _httpClient = new HttpClient();
            _httpClient.Timeout = TimeSpan.FromMinutes(10); // Védelem a timeout ellen
        }

        private void BtnBrowse_Click(object sender, RoutedEventArgs e)
        {
            using (var dialog = new System.Windows.Forms.FolderBrowserDialog())
            {
                dialog.Description = "Select your Stellar game main folder (12.41)";
                if (dialog.ShowDialog() == System.Windows.Forms.DialogResult.OK && !string.IsNullOrWhiteSpace(dialog.SelectedPath))
                {
                    TxtFolder.Text = dialog.SelectedPath;
                }
            }
        }

        private async void BtnStart_Click(object sender, RoutedEventArgs e)
        {
            string targetFolder = TxtFolder.Text;
            string base64Code = TxtCode.Text.Trim();

            if (string.IsNullOrEmpty(targetFolder) || !Directory.Exists(targetFolder))
            {
                System.Windows.MessageBox.Show("Please select a valid game directory first!", "Error", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            if (string.IsNullOrEmpty(base64Code))
            {
                System.Windows.MessageBox.Show("Please paste the download code generated by the website!", "Error", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            List<string> missingFiles;
            try
            {
                byte[] data = Convert.FromBase64String(base64Code);
                string jsonString = Encoding.UTF8.GetString(data);
                missingFiles = JsonSerializer.Deserialize<List<string>>(jsonString);
            }
            catch
            {
                System.Windows.MessageBox.Show("Invalid download code! Please copy it again from the build checker website.", "Decoder Error", MessageBoxButton.OK, MessageBoxImage.Error);
                return;
            }

            if (missingFiles == null || missingFiles.Count == 0)
            {
                System.Windows.MessageBox.Show("The code does not contain any missing files.", "Info", MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }

            // Gombok lezárása a letöltés idejére
            BtnStart.IsEnabled = false;
            BtnBrowse.IsEnabled = false;
            PrgBar.Value = 0;
            PrgBar.Maximum = missingFiles.Count;

            int successCount = 0;
            int failCount = 0;

            for (int i = 0; i < missingFiles.Count; i++)
            {
                string relativePath = missingFiles[i];
                string localFilePath = Path.Combine(targetFolder, relativePath);
                string localDirectory = Path.GetDirectoryName(localFilePath);

                if (!Directory.Exists(localDirectory))
                {
                    Directory.CreateDirectory(localDirectory);
                }

                LblStatus.Text = $"Downloading ({i + 1}/{missingFiles.Count}): {Path.GetFileName(relativePath)}...";

                string downloadUrl = GITHUB_BASE_RAW_URL + relativePath;
                bool downloaded = await DownloadFileAsync(downloadUrl, localFilePath);

                if (downloaded) successCount++;
                else failCount++;

                PrgBar.Value = i + 1;
            }

            BtnStart.IsEnabled = true;
            BtnBrowse.IsEnabled = true;
            LblStatus.Text = "Status: Finished.";

            if (failCount == 0)
            {
                System.Windows.MessageBox.Show($"Successfully downloaded all {successCount} missing file(s)! Your build is now complete.", "Success!", MessageBoxButton.OK, MessageBoxImage.Information);
            }
            else
            {
                System.Windows.MessageBox.Show($"Downloaded {successCount} file(s), but {failCount} file(s) failed. Please check your connection.", "Completed with errors", MessageBoxButton.OK, MessageBoxImage.Warning);
            }
        }

        private async Task<bool> DownloadFileAsync(string url, string outputPath)
        {
            try
            {
                using (var response = await _httpClient.GetAsync(url, HttpCompletionOption.ResponseHeadersRead))
                {
                    if (!response.IsSuccessStatusCode) return false;

                    using (var streamToReadFrom = await response.Content.ReadAsStreamAsync())
                    {
                        using (Stream streamToWriteTo = File.Open(outputPath, FileMode.Create, FileAccess.Write, FileShare.None))
                        {
                            await streamToReadFrom.CopyToAsync(streamToWriteTo);
                        }
                    }
                }
                return true;
            }
            catch
            {
                return false;
            }
        }
    }
}
